name: green_vegease
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  auto_route: ^9.2.1+1
  auto_route_generator: ^9.0.0
  dio: ^5.6.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_launcher_icons: ^0.13.1
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.10+1
  rename_app: ^1.6.1
  retrofit: ^4.2.0
  retrofit_generator: ^8.2.1
  
flutter_icons:
  android: "launch_icon"
  ios: true
  image_path : "assets/images/app_icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  fonts:
    - family: Gilroy-Regular
      fonts:
        - asset: assets\fonts\Gilroy-Regular.ttf
    - family: Gilroy-Medium
      fonts:
        - asset: assets\fonts\Gilroy-Medium.ttf 
    - family: Gilroy-Bold
      fonts:
        - asset: assets\fonts\Gilroy-Bold.ttf
    - family: Gilroy-SemiBold
      fonts:
        - asset: assets\fonts\Gilroy-SemiBold.ttf
    - family: Gilroy-Light
      fonts:
        - asset: assets\fonts\Gilroy-Light.ttf
    - family: Gilroy-ExtraBold
      fonts:
        - asset: assets\fonts\Gilroy-ExtraBold.ttf
        
  generate: true
  assets:
    - assets\images\login_background.png
    - assets\images\carrot.svg
    - assets\images\on_bording (1).png
    - assets\icons\back_arrow.svg
    - assets\images\colored_carrot.svg
    - assets\icons\forward_arrow.svg

