name: green_vegease
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  auto_route: ^9.2.1+1
  auto_route_generator: ^9.0.0
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.11

flutter:
  uses-material-design: true
  fonts:
    - family: Gilroy
      fonts:
        - asset: assets\fonts\Gilroy-Medium.ttf  
  generate: true
  assets:
    - assets\images\login_background.svg
    - assets\images\carrot.svg
    - assets\images\online groceriet.svg
    - assets\images\onbording.png

