// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA244mTeF0IS9fCB0BnmtXBrfxeoW9Jc5o',
    appId: '1:904183955352:web:54833f22cb8d6cba7635ed',
    messagingSenderId: '904183955352',
    projectId: 'green-vegease',
    authDomain: 'green-vegease.firebaseapp.com',
    storageBucket: 'green-vegease.appspot.com',
    measurementId: 'G-C3GWQ8GZ6E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnM0qLdjYmMow3S-0AkACGnVmgCKEEMYE',
    appId: '1:904183955352:android:bbdc2c610c2551d97635ed',
    messagingSenderId: '904183955352',
    projectId: 'green-vegease',
    storageBucket: 'green-vegease.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAy0ytCXUNCRExgZTDQ3BEDJ7rTxk91NR8',
    appId: '1:904183955352:ios:9ee3bbc9e0cbbe217635ed',
    messagingSenderId: '904183955352',
    projectId: 'green-vegease',
    storageBucket: 'green-vegease.appspot.com',
    iosBundleId: 'com.example.greenVegease',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAy0ytCXUNCRExgZTDQ3BEDJ7rTxk91NR8',
    appId: '1:904183955352:ios:9ee3bbc9e0cbbe217635ed',
    messagingSenderId: '904183955352',
    projectId: 'green-vegease',
    storageBucket: 'green-vegease.appspot.com',
    iosBundleId: 'com.example.greenVegease',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA244mTeF0IS9fCB0BnmtXBrfxeoW9Jc5o',
    appId: '1:904183955352:web:71a53fb4828199a77635ed',
    messagingSenderId: '904183955352',
    projectId: 'green-vegease',
    authDomain: 'green-vegease.firebaseapp.com',
    storageBucket: 'green-vegease.appspot.com',
    measurementId: 'G-2NY7F5ETV2',
  );

}